slam_toolbox:
  ros__parameters:
    solver_plugin: "solver_plugins::CeresSolver"
    ceres_linear_solver: "SPARSE_NORMAL_CHOLESKY"
    odom_frame: "odom"
    map_frame: "map"
    base_frame: "base_link"
    scan_topic: "/scan"
    use_scan_matching: true
    resolution: 0.05
    minimum_travel_distance: 0.2
    map_update_interval: 1.0
    transform_publish_period: 0.05
    map_publish_period: 2.0
    scan_queue_size: 10
